# Generated by Django 4.2.20 on 2025-04-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='學號')),
                ('birthdate', models.DateField(verbose_name='生日')),
                ('birth_time', models.TimeField(verbose_name='出生時間')),
                ('city', models.CharField(max_length=50, verbose_name='縣市')),
                ('town', models.CharField(max_length=50, verbose_name='鄉鎮')),
                ('goal', models.TextField(max_length=255, verbose_name='追求目標')),
            ],
        ),
    ]
